import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import mongoose from 'mongoose'; import axios from 'axios'; import * as cheerio from 'cheerio'; import rateLimit from 'express-rate-limit'; import cron from 'node-cron'; import { chromium } from 'playwright'; import robotsParser from 'robots-parser'; import OpenAI from 'openai';
const app=express(); app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json({limit:'2mb'})); app.use(rateLimit({windowMs:60000,max:60}));
const Company=mongoose.model('Company',new mongoose.Schema({name:String,website:String,description:String,industry:String,location:String,emails:[String],phones:[String],socialLinks:[String],technologies:[String],products:[String],services:[String],legalSignals:[String],marketSignals:[String],competitors:[String],sourceUrls:[String],enriched:Boolean,raw:Object,lastExtractedAt:Date},{timestamps:true}));
const Job=mongoose.model('Job',new mongoose.Schema({query:String,urls:[String],options:Object,schedule:String,status:String,resultCount:Number,error:String,startedAt:Date,finishedAt:Date},{timestamps:true}));
const Log=mongoose.model('Log',new mongoose.Schema({level:String,message:String,jobId:String,meta:Object},{timestamps:true}));
const uniq=a=>[...new Set((a||[]).filter(Boolean).map(x=>String(x).trim()).filter(Boolean))]; const sleep=ms=>new Promise(r=>setTimeout(r,ms)); let last=0;
async function log(level,message,jobId,meta={}){console.log(level,message);try{await Log.create({level,message,jobId,meta})}catch{}}
async function allowed(url){try{const u=new URL(url),r=await axios.get(`${u.protocol}//${u.host}/robots.txt`,{timeout:5000,validateStatus:()=>true});return r.status>=400||robotsParser(`${u.protocol}//${u.host}/robots.txt`,r.data).isAllowed(url,'CompanyIntelligenceBot')}catch{return true}}
async function fetchHtml(url,dynamic){if(!/^https?:\/\//i.test(url))throw Error('Invalid URL');if(!(await allowed(url)))throw Error('Blocked by robots.txt');await sleep(Math.max(0,1000-(Date.now()-last)));last=Date.now();if(!dynamic)return (await axios.get(url,{timeout:20000,headers:{'User-Agent':'CompanyIntelligenceBot/1.0'}})).data;const b=await chromium.launch({headless:true});try{const p=await b.newPage({userAgent:'CompanyIntelligenceBot/1.0'});await p.goto(url,{waitUntil:'domcontentloaded',timeout:20000});return await p.content()}finally{await b.close()}}
function extract(html,url){const $=cheerio.load(html);$('script,style,noscript,svg').remove();const text=$('body').text().replace(/\s+/g,' ').trim();const title=$('title').text().trim();const description=$('meta[name="description"]').attr('content')||$('meta[property="og:description"]').attr('content')||text.slice(0,500);const emails=uniq(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi));const phones=uniq(text.match(/(?:\+?\d[\d ().-]{7,}\d)/g)).filter(x=>x.replace(/\D/g,'').length>=8);const links=uniq($('a[href]').map((_,e)=>{try{return new URL($(e).attr('href'),url).href}catch{return null}}).get());const socialLinks=links.filter(x=>/(linkedin|twitter|x\.com|facebook|instagram|youtube)\.com/i.test(x));const headings=uniq($('h1,h2,h3').map((_,e)=>$(e).text()).get());const technologies=uniq([...(html.match(/React|Vue|Angular|Next\.js|Nuxt|WordPress|Shopify|Cloudflare|Google Analytics|Bootstrap|Tailwind CSS/gi)||[])]);const legalSignals=uniq(text.match(/incorporated|registered office|terms of service|privacy policy|copyright|LLC|Ltd\.?|Limited|Pvt\.? Ltd|Private Limited|Inc\.?/gi));const marketSignals=uniq(text.match(/customers|clients|industry|industries|market|revenue|funding|investors|partners|pricing|enterprise/gi));return{name:title||new URL(url).hostname,website:url,description,emails,phones,socialLinks,technologies,products:headings,services:headings,legalSignals,marketSignals,sourceUrls:[url],raw:{headings,links:links.slice(0,100)}}}
function links(html,base){const $=cheerio.load(html);return uniq($('a[href]').map((_,e)=>{try{return new URL($(e).attr('href'),base).href}catch{return null}}).get()).filter(u=>{try{const a=new URL(u),b=new URL(base);return a.hostname===b.hostname&&!/\.(pdf|jpg|jpeg|png|gif|zip)$/i.test(a.pathname)}catch{return false}})}
async function enrich(c){if(!process.env.OPENAI_API_KEY)return {...c,enriched:false};const o=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const r=await o.chat.completions.create({model:'gpt-4o-mini',response_format:{type:'json_object'},messages:[{role:'system',content:'Normalize business data. Never invent facts.'},{role:'user',content:`Return JSON keys description,industry,location,products,services,technologies,competitors,marketSignals,legalSignals. Unknown values must be empty.\n${JSON.stringify(c)}`} ]});return {...c,...JSON.parse(r.choices[0].message.content),enriched:true}}
async function run(job){const max=Math.min(Number(job.options?.maxPages||10),30),queue=[...job.urls],seen=new Set(),out=[];while(queue.length&&seen.size<max){const url=queue.shift();if(seen.has(url))continue;seen.add(url);try{await log('info',`Fetching ${url}`,job._id);const html=await fetchHtml(url,job.options?.dynamic);let c=extract(html,url);if(job.options?.discoverLinks)queue.push(...links(html,url).filter(x=>!seen.has(x)).slice(0,5));if(job.options?.pagination)queue.push(...links(html,url).filter(x=>/page|next|more/i.test(x)).slice(0,3));if(job.options?.enrich)c=await enrich(c);const saved=await Company.findOneAndUpdate({website:c.website},{$set:{...c,lastExtractedAt:new Date()}},{upsert:true,new:true});out.push(saved)}catch(e){await log('error',`${url}: ${e.message}`,job._id)}}return out}
async function execute(job){job.status='running';job.startedAt=new Date();await job.save();try{const r=await run(job);job.status='completed';job.resultCount=r.length;job.finishedAt=new Date();await job.save();return r}catch(e){job.status='failed';job.error=e.message;job.finishedAt=new Date();await job.save();throw e}}
const tasks=new Map();function schedule(job){if(!job.schedule||!cron.validate(job.schedule))return;tasks.get(String(job._id))?.stop();tasks.set(String(job._id),cron.schedule(job.schedule,()=>execute(job).catch(()=>{})))}
app.get('/api/health',(_,r)=>r.json({ok:true})); app.get('/api/companies',async(req,r)=>{const q=(req.query.q||'').trim();r.json(await Company.find(q?{$or:[{name:new RegExp(q,'i')},{industry:new RegExp(q,'i')},{website:new RegExp(q,'i')}]}:{}).sort({updatedAt:-1}).limit(200))}); app.get('/api/jobs',async(_,r)=>r.json(await Job.find().sort({createdAt:-1}).limit(100))); app.get('/api/logs',async(_,r)=>r.json(await Log.find().sort({createdAt:-1}).limit(300)));
app.post('/api/jobs',async(req,res)=>{try{const {query='',urls=[],options={},schedule:nullSchedule=null}=req.body;const valid=[...new Set(urls.filter(u=>/^https?:\/\//i.test(u)))];if(!valid.length)return res.status(400).json({error:'Provide at least one valid URL'});const job=await Job.create({query,urls:valid,options:{dynamic:false,discoverLinks:true,pagination:true,enrich:false,maxPages:10,...options},schedule:nullSchedule,status:nullSchedule?'scheduled':'queued'});if(nullSchedule){schedule(job);return res.status(201).json(job)}const results=await execute(job);res.status(201).json({job,results})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/jobs/:id/run',async(req,res)=>{try{const j=await Job.findById(req.params.id);if(!j)return res.status(404).json({error:'Not found'});res.json({job:j,results:await execute(j)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/export',async(req,res)=>{const rows=await Company.find().lean();if(req.query.format==='csv'){const f=['name','website','description','industry','location','emails','phones','technologies','products','services','competitors'];const esc=v=>`"${String(Array.isArray(v)?v.join('; '):v??'').replaceAll('"','""')}"`;return res.type('text/csv').send([f.join(','),...rows.map(x=>f.map(k=>esc(x[k])).join(','))].join('\n'))}res.json(rows)});
await mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/company_intelligence');for(const j of await Job.find({status:'scheduled',schedule:{$ne:null}}))schedule(j);app.listen(process.env.PORT||5000,()=>console.log('API on 5000'));
